class AppRoutes {
  static const home = '/home';
  static const consultant = '/consultant';
  static const login = '/login';
  static const signup = '/signup';
  static const verifyEmail = '/verify-email';
  static const profileCompletion = '/profile-completion';
  static const connections = '/connections';
  static const newSession = '/new-session';
  static const sessions = '/sessions';
  static const about = '/about';
  static const settings    = '/settings';
  static const preferences = '/settings/preferences';
  static const assistant   = '/settings/assistant';
  static const voiceAssistant = '/settings/voice-assistant';
  static const entities = '/entities';
  static const sessionAnalytics = '/session-analytics';
  static const roleplaySetup = '/roleplay-setup';
  static const quests = '/quests';
  static const gameCenter = '/game-center'; // Replaces quests as primary nav target
  static const graphExplorer = '/graph-explorer';
  static const healthDashboard = '/health-dashboard';
  static const expensesTracker = '/expenses-tracker';
  static const tasks = '/tasks';
  static const smartHome = '/smart-home';
  static const tripsPlanner = '/trips-planner';
  static const integrations = '/integrations';
  static const subscription = '/subscription';
  static const insights = '/insights';
  static const language    = '/settings/language';
  static const permissions = '/settings/permissions';
  static const data        = '/settings/data';
  static const updatePassword = '/update-password';
}
