-- =====================================================================
-- Bubbles-AI — Supabase / Postgres Schema (canonical)
-- =====================================================================
-- Last regenerated: 2026-05-08 (post Phase A drops + Phase B/D RLS hardening
-- + index tuning, via Supabase MCP introspection).
--
-- Apply on a fresh project:
--   psql "<connection-string>" -f db_schema.sql
--
-- Live state on project_ref czjwoqwbwtojlypbzupi was generated by:
--   1. Drop 21 unused tables (zero rows / zero code refs).
--   2. ENABLE RLS on all 37 remaining public.* tables, with policies.
--   3. Pin search_path on user-defined functions.
--   4. Add common-query indexes.
-- =====================================================================


-- ── Extensions ───────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS postgis;


-- ══════════════════════════════════════════════════════════════════════
-- TABLES (alphabetical)
-- ══════════════════════════════════════════════════════════════════════

CREATE TABLE public.achievements (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  title text NOT NULL,
  description text,
  icon text DEFAULT '🏆'::text,
  category text DEFAULT 'general'::text,
  criteria_type text NOT NULL,
  criteria_value integer NOT NULL,
  xp_reward integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  code text UNIQUE,
  tier text
);

CREATE TABLE public.app_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  rating integer CHECK (rating BETWEEN 1 AND 5),
  feedback_text text,
  app_version text,
  os_info text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  details jsonb,
  ip_address text,
  user_agent text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.coaching_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid,
  report_content jsonb NOT NULL DEFAULT '{}'::jsonb,
  areas_of_improvement text[],
  model_used text,
  user_talk_pct double precision,
  others_talk_pct double precision,
  key_topics text[],
  key_decisions text[],
  action_items text[],
  follow_up_people text[],
  filler_words text[],
  filler_word_count integer DEFAULT 0,
  tone_summary text,
  engagement_trend text,
  suggestions text[],
  strengths text[],
  report_text text,
  generated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.consultant_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid,
  query text,
  question text,
  response text,
  answer text,
  source_screen text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.entities (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  canonical_name text NOT NULL,
  display_name text,
  entity_type text NOT NULL,
  aliases text[],
  description text,
  mention_count integer DEFAULT 0,
  is_archived boolean DEFAULT false,
  last_seen_at timestamptz,
  created_at timestamptz DEFAULT now(),
  UNIQUE (user_id, canonical_name)
);

CREATE TABLE public.entity_attributes (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  entity_id uuid REFERENCES public.entities(id) ON DELETE CASCADE,
  attribute_key text NOT NULL,
  attribute_value text,
  value_type text DEFAULT 'string'::text,
  confidence numeric DEFAULT 1.0,
  source_session_id uuid,
  source_session text,
  updated_at timestamptz DEFAULT now(),
  UNIQUE (entity_id, attribute_key)
);

CREATE TABLE public.entity_relations (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  source_id uuid REFERENCES public.entities(id) ON DELETE CASCADE,
  target_id uuid REFERENCES public.entities(id) ON DELETE CASCADE,
  relation text NOT NULL,
  strength numeric DEFAULT 1.0,
  source_session text,
  updated_at timestamptz,
  created_at timestamptz DEFAULT now(),
  UNIQUE (source_id, target_id, relation)
);

CREATE TABLE public.entity_tags (
  entity_id uuid NOT NULL REFERENCES public.entities(id) ON DELETE CASCADE,
  tag_id uuid NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  PRIMARY KEY (entity_id, tag_id)
);

CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid,
  title text NOT NULL,
  description text,
  due_text text,
  start_time timestamptz,
  end_time timestamptz,
  location text,
  is_all_day boolean DEFAULT false,
  is_completed boolean DEFAULT false,
  external_event_id text,
  sync_provider text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid,
  log_id uuid,
  consultant_log_id uuid,
  feedback_type text,
  rating integer,
  value integer,
  comment text,
  idempotency_key text UNIQUE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.highlights (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid,
  highlight_type text NOT NULL,
  title text,
  body text,
  content text NOT NULL,
  priority integer DEFAULT 1,
  is_resolved boolean DEFAULT false,
  is_dismissed boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.knowledge_graphs (
  user_id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  graph_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.memory (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid,
  content text NOT NULL,
  memory_type text NOT NULL DEFAULT 'general'::text,
  embedding vector(384),
  importance numeric DEFAULT 1.0,
  confidence numeric DEFAULT 1.0,
  source text DEFAULT 'inferred'::text,
  is_pinned boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  last_accessed_at timestamptz,
  expires_at timestamptz
);

CREATE TABLE public.notification_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token text NOT NULL,
  device_type text,
  is_active boolean DEFAULT true,
  added_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (user_id, token)
);

CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  body text,
  notif_type text,
  action_url text,
  is_read boolean DEFAULT false,
  read_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.onboarding_progress (
  user_id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  has_completed_welcome boolean DEFAULT false,
  has_set_voice boolean DEFAULT false,
  has_connected_calendar boolean DEFAULT false,
  has_completed_tutorial boolean DEFAULT false,
  current_step text,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.performa (
  user_id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id),
  manual_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  ai_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  avatar_url text,
  dob date,
  gender text,
  country text,
  locale text DEFAULT 'en_US'::text,
  timezone text DEFAULT 'UTC'::text,
  occupation text,
  company text,
  bio text,
  is_developer boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.quest_definitions (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  title text NOT NULL,
  description text,
  quest_type text DEFAULT 'daily'::text,
  action_type text NOT NULL,
  target integer NOT NULL DEFAULT 1,
  xp_reward integer DEFAULT 0,
  is_active boolean DEFAULT true,
  focus_area text,
  difficulty text DEFAULT 'medium'::text,
  mission_type text DEFAULT 'action'::text,
  brief jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.rewards (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  title text NOT NULL,
  description text,
  icon text DEFAULT '🎁'::text,
  category text DEFAULT 'general'::text,
  cost_xp integer NOT NULL,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.sentiment_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid,
  turn_index integer NOT NULL,
  sentiment_score double precision,
  emotion_label text,
  speaker_role text,
  score double precision,
  label text,
  recorded_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.session_analytics (
  session_id uuid NOT NULL PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  total_turns integer DEFAULT 0,
  user_word_count integer DEFAULT 0,
  assistant_word_count integer DEFAULT 0,
  average_latency_ms integer,
  topic_summary text,
  user_turns integer DEFAULT 0,
  others_turns integer DEFAULT 0,
  llm_turns integer DEFAULT 0,
  avg_advice_latency_ms numeric,
  total_duration_seconds numeric,
  memories_saved integer DEFAULT 0,
  events_extracted integer DEFAULT 0,
  highlights_created integer DEFAULT 0,
  avg_sentiment_score numeric,
  dominant_sentiment text,
  computed_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.session_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  session_id uuid,
  turn_index integer DEFAULT 0,
  role text NOT NULL,
  content text,
  content_html text,
  model_used text,
  latency_ms integer,
  tokens_used integer,
  finish_reason text,
  has_error boolean DEFAULT false,
  error_message text,
  speaker_label text,
  confidence numeric,
  sentiment_score numeric,
  sentiment_label text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.session_tags (
  session_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  PRIMARY KEY (session_id, tag_id)
);

CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  title text,
  summary text,
  session_type text DEFAULT 'general'::text,
  mode text DEFAULT 'live_wingman'::text,
  device_id uuid,
  start_time timestamptz DEFAULT now(),
  end_time timestamptz,
  ended_at timestamptz,
  status text DEFAULT 'active'::text,
  is_starred boolean DEFAULT false,
  is_ephemeral boolean DEFAULT false,
  is_multiplayer boolean DEFAULT false,
  persona text DEFAULT 'casual'::text,
  sentiment_score numeric,
  token_usage_prompt integer DEFAULT 0,
  token_usage_completion integer DEFAULT 0,
  total_cost_usd numeric DEFAULT 0.0,
  created_at timestamptz DEFAULT now(),
  deleted_at timestamptz,
  idempotency_key text UNIQUE
);

CREATE TABLE public.tags (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  color text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (user_id, name)
);

CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  due_date timestamptz,
  priority text DEFAULT 'medium'::text,
  status text DEFAULT 'pending'::text,
  category text,
  source_session_id uuid,
  completed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.user_achievements (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  achievement_id uuid REFERENCES public.achievements(id) ON DELETE CASCADE,
  awarded_at timestamptz DEFAULT now(),
  UNIQUE (user_id, achievement_id)
);

CREATE TABLE public.user_devices (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  device_id text NOT NULL,
  device_model text,
  os_version text,
  app_version text,
  fcm_token text,
  apns_token text,
  last_ip_address text,
  last_location geometry(Point, 4326),
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  last_active_at timestamptz DEFAULT now(),
  UNIQUE (user_id, device_id)
);

CREATE TABLE public.user_gamification (
  user_id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  total_xp integer DEFAULT 0,
  level integer DEFAULT 1,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  streak_freezes integer DEFAULT 1,
  last_active_date date,
  xp_spent integer DEFAULT 0,
  leaderboard_opt_in boolean DEFAULT true,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.user_mistakes (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid REFERENCES public.sessions(id) ON DELETE SET NULL,
  rule_id text NOT NULL,
  category text NOT NULL,
  snippet text NOT NULL,
  suggestion text,
  source text NOT NULL CHECK (source IN ('lt','llm')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.user_quests (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  quest_id uuid REFERENCES public.quest_definitions(id) ON DELETE CASCADE,
  progress integer DEFAULT 0,
  target integer NOT NULL,
  is_completed boolean DEFAULT false,
  xp_awarded boolean DEFAULT false,
  assigned_date date NOT NULL,
  completed_at timestamptz,
  reason text,
  brief_state jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.user_rewards (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  reward_id uuid REFERENCES public.rewards(id) ON DELETE CASCADE,
  cost_xp integer NOT NULL,
  unlocked_at timestamptz DEFAULT now(),
  UNIQUE (user_id, reward_id)
);

CREATE TABLE public.user_settings (
  user_id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  theme text DEFAULT 'system'::text,
  accent_color text,
  font_size text DEFAULT 'medium'::text,
  voice_assistant_name text DEFAULT 'Bubbles'::text,
  assistant_persona text DEFAULT 'friendly'::text,
  assistant_voice_id text,
  speech_rate numeric DEFAULT 1.0,
  pitch numeric DEFAULT 1.0,
  haptic_feedback boolean DEFAULT true,
  auto_play_audio boolean DEFAULT true,
  transcription_language text DEFAULT 'en-US'::text,
  enable_nsfw_filter boolean DEFAULT true,
  data_sharing_opt_in boolean DEFAULT false,
  reminder_hour smallint DEFAULT 19,
  reminder_timezone text DEFAULT 'UTC'::text,
  last_reminder_sent_date date,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.voice_enrollments (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  embedding vector(192) NOT NULL,
  samples_count integer DEFAULT 0,
  model_version text,
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.xp_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  amount integer NOT NULL,
  source_type text NOT NULL,
  source_id text,
  description text,
  created_at timestamptz DEFAULT now()
);


-- ── Cross-table foreign keys (deferred to avoid order issues) ──────────
ALTER TABLE public.coaching_reports
  ADD CONSTRAINT coaching_reports_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;

ALTER TABLE public.consultant_logs
  ADD CONSTRAINT consultant_logs_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;

ALTER TABLE public.entity_attributes
  ADD CONSTRAINT entity_attributes_source_session_id_fkey
  FOREIGN KEY (source_session_id) REFERENCES public.sessions(id);

ALTER TABLE public.entity_tags
  ADD CONSTRAINT entity_tags_tag_id_fkey
  FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;

ALTER TABLE public.events
  ADD CONSTRAINT events_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;

ALTER TABLE public.feedback
  ADD CONSTRAINT feedback_consultant_log_id_fkey
  FOREIGN KEY (consultant_log_id) REFERENCES public.consultant_logs(id) ON DELETE CASCADE,
  ADD CONSTRAINT feedback_log_id_fkey
  FOREIGN KEY (log_id) REFERENCES public.session_logs(id) ON DELETE CASCADE,
  ADD CONSTRAINT feedback_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;

ALTER TABLE public.highlights
  ADD CONSTRAINT highlights_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;

ALTER TABLE public.memory
  ADD CONSTRAINT memory_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;

ALTER TABLE public.sentiment_logs
  ADD CONSTRAINT sentiment_logs_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;

ALTER TABLE public.session_analytics
  ADD CONSTRAINT session_analytics_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;

ALTER TABLE public.session_logs
  ADD CONSTRAINT session_logs_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE;

ALTER TABLE public.session_tags
  ADD CONSTRAINT session_tags_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE CASCADE,
  ADD CONSTRAINT session_tags_tag_id_fkey
  FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;

ALTER TABLE public.sessions
  ADD CONSTRAINT sessions_device_id_fkey
  FOREIGN KEY (device_id) REFERENCES public.user_devices(id);

ALTER TABLE public.tasks
  ADD CONSTRAINT tasks_source_session_id_fkey
  FOREIGN KEY (source_session_id) REFERENCES public.sessions(id);


-- ══════════════════════════════════════════════════════════════════════
-- INDEXES
-- ══════════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_audit_log_user_time
  ON public.audit_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consultant_logs_user
  ON public.consultant_logs (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_entities_canonical
  ON public.entities (user_id, canonical_name);
CREATE INDEX IF NOT EXISTS idx_entities_user
  ON public.entities (user_id, entity_type);
CREATE INDEX IF NOT EXISTS idx_events_session
  ON public.events (session_id);
CREATE INDEX IF NOT EXISTS idx_events_user_time
  ON public.events (user_id, start_time);
CREATE INDEX IF NOT EXISTS idx_feedback_session
  ON public.feedback (session_id);
CREATE INDEX IF NOT EXISTS idx_highlights_user
  ON public.highlights (user_id, is_resolved);
CREATE INDEX IF NOT EXISTS idx_memory_session
  ON public.memory (user_id, session_id);
CREATE INDEX IF NOT EXISTS idx_memory_user_time
  ON public.memory (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_vector
  ON public.memory USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_notifications_unread
  ON public.notifications (user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_user_time
  ON public.notifications (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quest_defs_focus_active
  ON public.quest_definitions (focus_area, difficulty) WHERE is_active;
CREATE INDEX IF NOT EXISTS idx_sentiment_logs_session
  ON public.sentiment_logs (session_id, turn_index);
CREATE INDEX IF NOT EXISTS idx_session_logs_session_turn
  ON public.session_logs (session_id, turn_index);
CREATE INDEX IF NOT EXISTS idx_sessions_mode
  ON public.sessions (user_id, mode);
CREATE INDEX IF NOT EXISTS idx_sessions_user_created
  ON public.sessions (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_user_status
  ON public.tasks (user_id, status, due_date);
CREATE INDEX IF NOT EXISTS idx_user_mistakes_category
  ON public.user_mistakes (user_id, category);
CREATE INDEX IF NOT EXISTS idx_user_mistakes_user_time
  ON public.user_mistakes (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_quests_user_date
  ON public.user_quests (user_id, assigned_date);
CREATE INDEX IF NOT EXISTS idx_user_rewards_user
  ON public.user_rewards (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_xp_transactions_dedup
  ON public.xp_transactions (user_id, source_type, source_id)
  WHERE source_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_xp_transactions_period
  ON public.xp_transactions (created_at, user_id) WHERE amount > 0;
CREATE INDEX IF NOT EXISTS idx_xp_transactions_user
  ON public.xp_transactions (user_id, source_type, created_at);
CREATE INDEX IF NOT EXISTS idx_xp_transactions_user_time
  ON public.xp_transactions (user_id, created_at DESC);


-- ══════════════════════════════════════════════════════════════════════
-- FUNCTIONS  (search_path pinned to prevent privilege escalation)
-- ══════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.get_user_stats(p_user_id uuid)
RETURNS TABLE (
  total_sessions bigint,
  total_memories bigint,
  total_entities bigint,
  total_highlights bigint,
  open_events bigint
)
LANGUAGE sql STABLE SET search_path = public, pg_temp
AS $$
  SELECT
    (SELECT count(*) FROM public.sessions   WHERE user_id = p_user_id AND deleted_at IS NULL),
    (SELECT count(*) FROM public.memory     WHERE user_id = p_user_id AND is_archived = false),
    (SELECT count(*) FROM public.entities   WHERE user_id = p_user_id AND is_archived = false),
    (SELECT count(*) FROM public.highlights WHERE user_id = p_user_id AND is_dismissed = false AND is_resolved = false),
    (SELECT count(*) FROM public.events     WHERE user_id = p_user_id AND is_completed = false);
$$;

CREATE OR REPLACE FUNCTION public.match_memory(
  query_embedding vector,
  match_threshold double precision,
  match_count integer,
  p_user_id uuid
)
RETURNS TABLE (id uuid, content text, similarity double precision)
LANGUAGE plpgsql SET search_path = public, pg_temp
AS $$
BEGIN
  RETURN QUERY
  SELECT m.id, m.content,
         1 - (m.embedding <=> query_embedding) AS similarity
  FROM public.memory m
  WHERE m.user_id = p_user_id
    AND m.is_archived = false
    AND 1 - (m.embedding <=> query_embedding) > match_threshold
  ORDER BY m.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.match_memory_typed(
  query_embedding vector,
  match_threshold double precision,
  match_count integer,
  p_user_id uuid,
  p_memory_type text
)
RETURNS TABLE (id uuid, content text, memory_type text, importance double precision, similarity double precision)
LANGUAGE sql STABLE SET search_path = public, pg_temp
AS $$
  SELECT id, content, memory_type, importance,
         1 - (embedding <=> query_embedding) AS similarity
  FROM public.memory
  WHERE user_id = p_user_id
    AND memory_type = p_memory_type
    AND is_archived = false
    AND (expires_at IS NULL OR expires_at > now())
    AND 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;

CREATE OR REPLACE FUNCTION public.match_voice(
  query_embedding vector,
  match_threshold double precision,
  match_count integer
)
RETURNS TABLE (user_id uuid, similarity double precision)
LANGUAGE sql STABLE SET search_path = public, pg_temp
AS $$
  SELECT user_id,
         1 - (embedding <=> query_embedding) AS similarity
  FROM public.voice_enrollments
  WHERE 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;

CREATE OR REPLACE FUNCTION public.top_mistake_categories(p_user uuid, p_days integer)
RETURNS TABLE (category text, n integer)
LANGUAGE sql STABLE SET search_path = public, pg_temp
AS $$
  SELECT category, count(*)::int AS n
  FROM public.user_mistakes
  WHERE user_id = p_user
    AND created_at > now() - (p_days || ' days')::interval
  GROUP BY category
  ORDER BY count(*) DESC
  LIMIT 3;
$$;


-- ══════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ══════════════════════════════════════════════════════════════════════
-- Backend (service-role key) bypasses RLS entirely. Policies below gate
-- only the anon / authenticated client roles used by supabase-flutter.

-- Per-user (own-row) policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_own" ON public.profiles
  FOR ALL TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_settings_own" ON public.user_settings
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.user_devices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_devices_own" ON public.user_devices
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.onboarding_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "onboarding_progress_own" ON public.onboarding_progress
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "sessions_own" ON public.sessions
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.consultant_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "consultant_logs_own" ON public.consultant_logs
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.session_analytics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "session_analytics_own" ON public.session_analytics
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.memory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "memory_own" ON public.memory
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.knowledge_graphs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "knowledge_graphs_own" ON public.knowledge_graphs
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.entities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "entities_own" ON public.entities
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.entity_relations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "entity_relations_own" ON public.entity_relations
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.highlights ENABLE ROW LEVEL SECURITY;
CREATE POLICY "highlights_own" ON public.highlights
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tasks_own" ON public.tasks
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "events_own" ON public.events
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "feedback_own" ON public.feedback
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.sentiment_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "sentiment_logs_own" ON public.sentiment_logs
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.voice_enrollments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "voice_enrollments_own" ON public.voice_enrollments
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.notification_tokens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notification_tokens_own" ON public.notification_tokens
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notifications_own" ON public.notifications
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.coaching_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "coaching_reports_own" ON public.coaching_reports
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tags_own" ON public.tags
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.session_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "session_tags_own" ON public.session_tags
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.entity_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "entity_tags_own" ON public.entity_tags
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.app_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "app_feedback_own" ON public.app_feedback
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.user_gamification ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_gamification_own" ON public.user_gamification
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.user_quests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_quests_own" ON public.user_quests
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.user_rewards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_rewards_own" ON public.user_rewards
  FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

ALTER TABLE public.performa ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own performa" ON public.performa
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Read-own (clients cannot mutate; backend writes via service role)
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "audit_log_read_own" ON public.audit_log
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

ALTER TABLE public.xp_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "xp_transactions_own" ON public.xp_transactions
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_achievements_own" ON public.user_achievements
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

ALTER TABLE public.user_mistakes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_mistakes_own" ON public.user_mistakes
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- Session-scoped policies (joined through sessions.user_id / entities.user_id)
ALTER TABLE public.session_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "session_logs_via_session" ON public.session_logs
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.sessions s
                 WHERE s.id = session_logs.session_id AND s.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.sessions s
                      WHERE s.id = session_logs.session_id AND s.user_id = auth.uid()));

ALTER TABLE public.entity_attributes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "entity_attributes_via_entity" ON public.entity_attributes
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.entities e
                 WHERE e.id = entity_attributes.entity_id AND e.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.entities e
                      WHERE e.id = entity_attributes.entity_id AND e.user_id = auth.uid()));

-- Read-only public catalogs (definitions / catalog data only)
ALTER TABLE public.quest_definitions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "quest_definitions_read_all" ON public.quest_definitions
  FOR SELECT TO authenticated USING (true);

ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "achievements_read_all" ON public.achievements
  FOR SELECT TO authenticated USING (true);

ALTER TABLE public.rewards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "rewards_read_all" ON public.rewards
  FOR SELECT TO authenticated USING (true);


-- ══════════════════════════════════════════════════════════════════════
-- STORAGE  (avatars bucket; public read via CDN URL only — no listing)
-- ══════════════════════════════════════════════════════════════════════
-- Bucket itself created via Supabase dashboard. Policies on storage.objects
-- below restrict mutations to the user's own folder. Public CDN access works
-- regardless (the bucket is public).
--
-- "Public can view avatars" SELECT policy was intentionally removed to
-- prevent file listing.

-- (Policies below assumed already present from earlier setup; included for
-- completeness on a fresh project.)
--
-- CREATE POLICY "Users can upload their own avatar"
--   ON storage.objects FOR INSERT TO authenticated
--   WITH CHECK (bucket_id = 'avatars'
--               AND (auth.uid())::text = (storage.foldername(name))[1]);
-- CREATE POLICY "Users can update their own avatar"
--   ON storage.objects FOR UPDATE TO authenticated
--   USING (bucket_id = 'avatars'
--           AND (auth.uid())::text = (storage.foldername(name))[1]);
-- CREATE POLICY "Users can delete their own avatar"
--   ON storage.objects FOR DELETE TO authenticated
--   USING (bucket_id = 'avatars'
--           AND (auth.uid())::text = (storage.foldername(name))[1]);
